server:
  port: 9082
  servlet:
    context-path: /api
spring:
  # DB
  datasource:
    url:  jdbc:mysql://localhost:3306/calculadora
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    username: root
    password: admin
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

